In [23]:
import numpy as np

# 编程 4.1-1

In [24]:
A=np.array([[3,-1,2],
            [4,1,0],
            [-3,2,1],
            [1,1,5],
            [-2,0,3]])
b=np.array([[10,10,-5,15,0]]).T

In [25]:
x=np.dot(np.linalg.inv(A.T.dot(A)),A.T.dot(b))
print(x)

[[2.5246085 ]
 [0.66163311]
 [2.09340045]]


In [26]:
e=np.linalg.norm(b-A.dot(x))
print(e)

2.413492090641353


# 编程4.1-9

In [32]:
x = np.linspace(2, 4, 11).reshape(11, 1)
def fit(x, d):
    A = np.ones_like(x)
    for i in range(d):
        A = np.column_stack((A, np.power(x, i+1)))
    b = A.dot(np.ones((d+1,1)))
    return A,b

In [34]:
A,b=fit(x,5)
print(np.dot(np.linalg.inv(A.T.dot(A)), A.T.dot(b)))
np.linalg.cond(A.T.dot(A))

[[1.00073242]
 [0.99938965]
 [1.00006104]
 [1.00004578]
 [0.99999523]
 [1.00000012]]


27242729218275.67

可以精确到到小数点后2位，因为cond~1e14

In [35]:
A,b=fit(x,6)
print(np.dot(np.linalg.inv(A.T.dot(A)), A.T.dot(b)))
np.linalg.cond(A.T.dot(A))

[[0.16796875]
 [1.625     ]
 [0.890625  ]
 [0.98046875]
 [1.0078125 ]
 [0.99914551]
 [1.00003052]]


2.538626958278206e+16

可以精确到到小数点后0位，因为cond~1e16

In [36]:
A,b=fit(x,8)
print(np.dot(np.linalg.inv(A.T.dot(A)), A.T.dot(b)))
np.linalg.cond(A.T.dot(A))

[[ 1.42772000e+05]
 [-1.97440000e+04]
 [-1.58880000e+04]
 [ 3.82400000e+03]
 [-7.60000000e+01]
 [-1.77000000e+02]
 [ 4.47500000e+01]
 [-4.09375000e+00]
 [ 1.20507812e+00]]


1.41537084609883e+19

In [ ]:
无法精确到小数点后，因为cond>>1e16