In [69]:
import numpy as np

## 编程 2.7-5

In [70]:
def Newton_Method(F, DF, x, errorArg=1e-6):
    error=1
    while error>errorArg:
        s = np.linalg.inv(DF(x)).dot(F(x))
        error=np.linalg.norm(s, ord=np.inf, keepdims=False)
        x -= s
    return x

## (a)
$$(x-1)^2+(y-1)^2+z^2=1$$
$$(x-1)^2+y^2+(z-1)^2=1$$
$$x^2+(y-1)^2+(z-1)^2=1$$

In [71]:
def Fa(r):
    x=r[0]
    y=r[1]
    z=r[2]
    f1=(x-1)**2+(y-1)**2+z**2-1
    f2=(x-1)**2+y**2+(z-1)**2-1
    f3=x**2+(y-1)**2+(z-1)**2-1
    return np.array([f1,f2,f3])

def DFa(r):
    x=r[0]
    y=r[1]
    z=r[2]
    df1=np.array([2*x-2,2*y-2,2*z])
    df2=np.array([2*x-2,2*y,2*z-2])
    df3=np.array([2*x,2*y-2,2*z-2])
    return np.array([df1,df2,df3])

In [72]:
x=np.array([0.,0.,0.])
print(Newton_Method(Fa, DFa, x,))
x=np.array([2.,2.,2.])
print(Newton_Method(Fa, DFa, x,))

[0.33333333 0.33333333 0.33333333]
[1. 1. 1.]


## (b)
$$(x-1)^2+(y+2)^2+z^2=25$$
$$(x+2)^2+(y-2)^2+(z+1)^2=25$$
$$(x-4)^2+(y+2)^2+(z-3)^2=25$$

In [73]:
def Fb(r):
    x=r[0]
    y=r[1]
    z=r[2]
    f1=(x-1)**2+(y+2)**2+z**2-25
    f2=(x+2)**2+(y-2)**2+(z+1)**2-25
    f3=(x-4)**2+(y+2)**2+(z-3)**2-25
    return np.array([f1,f2,f3])

def DFb(r):
    x=r[0]
    y=r[1]
    z=r[2]
    df1=np.array([2*x-2,2*y+4,2*z])
    df2=np.array([2*x+4,2*y-4,2*z+2])
    df3=np.array([2*x-8,2*y+4,2*z-6])
    return np.array([df1,df2,df3])

In [74]:
x=np.array([0.,0.,1.])
print(Newton_Method(Fb, DFb, x))
x=np.array([2.,2.,2.])
print(Newton_Method(Fb, DFb, x))

[1. 2. 3.]
[1.88888889 2.44444444 2.11111111]


## 编程 2.7-9

In [75]:
def Broyden_Method_I(F, DF, x, A, errorArg=1e-6):
    error=1
    n=len(x)
    while error>errorArg:
        d_i = -np.linalg.inv(A).dot(F(x))
        D_i = F(x + d_i) - F(x)
        A += (D_i - A.dot(d_i)).reshape(n, 1).dot(d_i.reshape(1, n)) / d_i.dot(d_i)
        error=np.linalg.norm(d_i, ord=np.inf, keepdims=False)
        x += d_i
    return x

## (a)

In [84]:
A=np.identity(3)
x=np.array([0.,0.,0.])
print(Broyden_Method_I(Fa, DFa, x, A, errorArg=1e-5))
x=np.array([2.,2.,2.])
print(Broyden_Method_I(Fa, DFa, x, A, errorArg=1e-5))

[0.33333333 0.33333333 0.33333333]
[1.00000092 1.00000002 0.99999894]


## (b)

In [90]:
A=np.identity(3)
x=np.array([0.,0.,0.])
print(Broyden_Method_I(Fb, DFb, x, A, errorArg=1e-5))
x=np.array([3.,3.,3.])
print(Broyden_Method_I(Fb, DFb, x, A, errorArg=1e-5))

[0.99999982 1.99999991 3.00000018]
[1.88888889 2.44444444 2.11111111]


## 编程 2.7-11

In [ ]:
def Broyden_Method_II(F, DF, x, A, errorArg=1e-6):
    error=1
    n=len(x)
    while error>errorArg:
        d_i = -np.linalg.inv(A).dot(F(x))
        D_i = F(x + d_i) - F(x)
        A += (D_i - A.dot(d_i)).reshape(n, 1).dot(d_i.reshape(1, n)) / d_i.dot(d_i)
        error=np.linalg.norm(d_i, ord=np.inf, keepdims=False)
        x += d_i
    return x