In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.misc import derivative

## 编程 2.3-1

In [22]:
def new_A(n):
    A=np.ones([n,n],dtype='float64')
    for i in range(1,n+1):
       for j in range(1,n+1):
           A[i-1,j-1]=5/(i+2*j-1)
    return A

def new_x(n):
    return np.ones([n,1],dtype='float64')

[[2.5        1.25       0.83333333 0.625      0.5        0.41666667]
 [1.66666667 1.         0.71428571 0.55555556 0.45454545 0.38461538]
 [1.25       0.83333333 0.625      0.5        0.41666667 0.35714286]
 [1.         0.71428571 0.55555556 0.45454545 0.38461538 0.33333333]
 [0.83333333 0.625      0.5        0.41666667 0.35714286 0.3125    ]
 [0.71428571 0.55555556 0.45454545 0.38461538 0.33333333 0.29411765]]
[[6.125     ]
 [4.77566878]
 [3.98214286]
 [3.44233544]
 [3.04464286]
 [2.73645309]]


In [45]:
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape
    for i in range(m):  #化为上三角矩阵
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]
    for i in range(m-1, 0, -1): # 化为对角矩阵
        for j in range(i):
            A[j] -= A[j, i]*A[i]
    return A

def FE(x,xa):
    return np.max(x-xa)/np.max(x)

def BE(b,A,xa):
    return np.max(b-A.dot(xa))/np.max(b)

# (a) n=6

In [71]:
A=new_A(6)
x=new_x(6)
b=A.dot(x)
xa=Gaussian_elimination(np.column_stack((A,b)))[:,6]
print(xa)
print('FE=  %12e'%FE(x,xa))
print('BE=  %12e'%BE(b,A,xa))
print('EMF= %12e'%(FE(x,xa)/BE(b,A,xa)))
print('cond=%12e'%(np.linalg.norm(A,ord=np.inf)*np.linalg.norm(np.linalg.inv(A),ord=np.inf)))

[1. 1. 1. 1. 1. 1.]
FE=  3.477170e-10
BE=  5.532321e-01
EMF= 6.285191e-10
cond=7.034201e+07


# (b) n=10

In [72]:
A=new_A(10)
x=new_x(10)
b=A.dot(x)
xa=Gaussian_elimination(np.column_stack((A,b)))[:,10]
print(xa)
print('FE=  %12e'%FE(x,xa))
print('BE=  %12e'%BE(b,A,xa))
print('EMF= %12e'%(FE(x,xa)/BE(b,A,xa)))
print('cond=%12e'%(np.linalg.norm(A,ord=np.inf)*np.linalg.norm(np.linalg.inv(A),ord=np.inf)))

[1.         0.99999999 1.00000042 0.9999953  1.00002606 0.99992001
 1.00014268 0.9998529  1.00008127 0.99998139]
FE=  1.471040e-04
BE=  6.254169e-01
EMF= 2.352096e-04
cond=1.313701e+14


In [76]:
A=new_A(11)
x=new_x(11)
b=A.dot(x)
xa=Gaussian_elimination(np.column_stack((A,b)))[:,11]
print(xa)

[1.         1.00000043 0.99997962 1.00034974 0.99710929 1.01317854
 0.96453429 1.05768147 0.944362   1.02926817 0.99353631]


## 编程 2.3-5

In [77]:
A=new_A(12)
x=new_x(12)
b=A.dot(x)
xa=Gaussian_elimination(np.column_stack((A,b)))[:,12]
print(xa)

[ 0.99999999  1.00000329  0.99981486  1.00385949  0.96073181  1.22420618
  0.22551718  2.67828311 -1.29303843  2.91626627  0.10615844  1.1781989 ]


所以当n>=12时，没有正确的有效数字