In [3]:
import numpy as np
A=np.array([[5,2, 3],
             [4,5,6],[7,5,9]],dtype=float)
A[[0,2], :] = A[[2,0], :]
print(A)
print(A[1:,1])
print('max=',np.max(A[1:,1]))

id=np.where(A[1:,1]==5)
print('new: ',A[1:,1])
print('5 position: ',id)

print('最大行号： ',id[0][0]+1)

[[7. 5. 9.]
 [4. 5. 6.]
 [5. 2. 3.]]
[5. 2.]
max= 5.0
new:  [5. 2.]
5 position:  (array([0]),)
最大行号：  1


# 高斯消元

In [4]:
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape

    for i in range(m):  #化为上三角矩阵
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]

    for i in range(m-1, 0, -1): # 化为对角矩阵
        for j in range(i):
            A[j] -= A[j, i]*A[i]
            
    return A

# LU分解

In [5]:
def LU(A):
    m = A.shape[0]
    L = np.identity(m)
    U = A.copy()

    for i in range(m):
        for j in range(i+1, m):
            if U[i, i] == 0:
                raise ValueError("The matrix contains a zero pivot.")
            a = U[j, i] / U[i, i]
            L[j, i] = a
            U[j] -= a * U[i]
    
    return L, U

def Lsolve(L,b):
    m,n=L.shape
    k=b.size
    x=np.zeros(k)
    print(m,n,k)
    
    for i in range(0,n,1):
        x[i]=b[i]
        for j in range(0,i,1):
            x[i]=x[i]-L[i,j]*x[j]
        x[i]=x[i]/L[i,i]
        print(x[i])
    return x

def Usolve(U,b):
    m,n=U.shape
    k=b.size
    x=np.zeros(k)
    print(m,n,k)
    
    for i in range(n-1,-1,-1):
        x[i]=b[i]
        for j in range(i+1,n,1):
            x[i]=x[i]-U[i,j]*x[j]
        x[i]=x[i]/U[i,i]
    return x

# PLU分解

In [6]:
def PLU(A):
    m = A.shape[0]
    L = np.zeros((m,m))
    U = A.copy()
    P = np.identity(m)
    for i in range(m):
        # add permutation
        id=np.where(abs(U[i:,i])==np.max(abs(U[i:,i])))
        #print(id,'At: ',i)
        rmax=id[0][0]+i
        if(rmax!=i):
            U[[i,rmax], :] = U[[rmax,i], :]
            P[[i,rmax], :] = P[[rmax,i], :]
            L[[i,rmax], :] = L[[rmax,i], :]
        #print('P=',P)
        # UL factorization
        for j in range(i+1, m):
            if U[i, i] == 0:
                raise ValueError("The matrix contains a zero pivot.")
            a = U[j, i] / U[i, i]
            L[j, i] = a
            U[j] -= a * U[i]
    L=L+np.identity(m)
    return P, L, U

In [7]:
import numpy as np
A=np.array([[2,1, 5],
             [4,4,-4],[1,3,1]],dtype=float)
b=np.array([5,0, 6],dtype=float)
b2=np.expand_dims(b,axis=0)
B=np.concatenate((A,b2.T),axis=1)

In [8]:
print("x:", Gaussian_elimination(B)[:, -1])

x: [-1.  2.  1.]


In [9]:
L,U=LU(A)
y=Lsolve(L,b)
x=Usolve(U,y)
print('x=',x)

3 3 3
5.0
-10.0
16.0
3 3 3
x= [-1.  2.  1.]


In [10]:
P, L, U=PLU(A)
y=Lsolve(L, np.dot(P,b))
x=Usolve(U,y)
print('x=',x)

3 3 3
0.0
6.0
8.0
3 3 3
x= [-1.  2.  1.]


# 雅可比迭代

In [42]:
import numpy as np
def Jacobi(A, b2, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    print(D)
    print(np.diag(D))
    R = A - np.diag(D)
    x_i = initial_guess * np.ones(n)
    for i in range(iter_n):
        print('x_',i,'=',x_i)
        x_i = (b2 - R.dot(x_i)) / D
    
    return x_i

In [16]:

A=np.array([3,2])
B=np.array([1,4])
print(A/B)


[3.  0.5]


In [43]:
A=np.array([[3, 1],
             [1,2]])
b=np.array([5,5])
x0=np.array([0,0])
print(Jacobi(A,b,20,x0))

[3 2]
[[3 0]
 [0 2]]
x_ 0 = [0. 0.]
x_ 1 = [1.66666667 2.5       ]
x_ 2 = [0.83333333 1.66666667]
x_ 3 = [1.11111111 2.08333333]
x_ 4 = [0.97222222 1.94444444]
x_ 5 = [1.01851852 2.01388889]
x_ 6 = [0.99537037 1.99074074]
x_ 7 = [1.00308642 2.00231481]
x_ 8 = [0.9992284  1.99845679]
x_ 9 = [1.0005144 2.0003858]
x_ 10 = [0.9998714 1.9997428]
x_ 11 = [1.00008573 2.0000643 ]
x_ 12 = [0.99997857 1.99995713]
x_ 13 = [1.00001429 2.00001072]
x_ 14 = [0.99999643 1.99999286]
x_ 15 = [1.00000238 2.00000179]
x_ 16 = [0.9999994  1.99999881]
x_ 17 = [1.0000004 2.0000003]
x_ 18 = [0.9999999 1.9999998]
x_ 19 = [1.00000007 2.00000005]
[0.99999998 1.99999997]


In [28]:
A=np.array([[3, 1],
             [1,2]])
A[[0,1],:]=A[[1,0],:]
print('A=',A)
b=np.array([5,5])
x0=np.array([0,0])
print(Jacobi(A,b,20,x0))

A= [[1 2]
 [3 1]]
[1 1]
[[1 0]
 [0 1]]
x_ 0 = [0. 0.]
x_ 1 = [5. 5.]
x_ 2 = [ -5. -10.]
x_ 3 = [25. 20.]
x_ 4 = [-35. -70.]
x_ 5 = [145. 110.]
x_ 6 = [-215. -430.]
x_ 7 = [865. 650.]
x_ 8 = [-1295. -2590.]
x_ 9 = [5185. 3890.]
x_ 10 = [ -7775. -15550.]
x_ 11 = [31105. 23330.]
x_ 12 = [-46655. -93310.]
x_ 13 = [186625. 139970.]
x_ 14 = [-279935. -559870.]
x_ 15 = [1119745.  839810.]
x_ 16 = [-1679615. -3359230.]
x_ 17 = [6718465. 5038850.]
x_ 18 = [-10077695. -20155390.]
x_ 19 = [40310785. 30233090.]
[-6.0466175e+07 -1.2093235e+08]


# 例2

In [29]:
def A_ij(n):
    A = np.ones((n, n))
    for i in range(n):
        A[i, i] = n+1
    return A

def b_i(n):
    b=2*n*np.ones(n)
    return b

def x0(n):
    return np.zeros(n)

In [30]:
print(A_ij(5),b_i(5),x0(5))

[[6. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1.]
 [1. 1. 6. 1. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 6.]] [10. 10. 10. 10. 10.] [0. 0. 0. 0. 0.]


In [32]:
def Jacobi(A, b2, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    print(D)
    print(np.diag(D))
    R = A - np.diag(D)
    x_i = initial_guess * np.ones(n)
    for i in range(iter_n):
#        print('x_',i,'=',x_i)
        x_i = (b2 - R.dot(x_i)) / D
    
    return x_i

In [34]:
n=100
print(Jacobi(A_ij(n),b_i(n),70,x0(n)))

[101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101. 101.
 101. 101.]
[[101.   0.   0. ...   0.   0.   0.]
 [  0. 101.   0. ...   0.   0.   0.]
 [  0.   0. 101. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 101.   0.   0.]
 [  0.   0.   0. ...   0. 101.   0.]
 [  0.   0.   0. ...   0.   0. 101.]]
[0.75341454 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454
 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454
 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454
 0.75341454 0.75341454 0.75341454 0.75341454 0.75341454 0.7534

In [37]:
print(Gauss_Seidel(A_ij(n),b_i(n),30,x0(n)))

x_ 0 = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
x_ 1 = [1.98019802 1.9605921  1.9411803  1.92196069 1.90293138 1.88409047
 1.86543611 1.84696644 1.82867965 1.81057391 1.79264744 1.77489845
 1.7573252  1.73992594 1.72269895 1.70564252 1.68875497 1.67203463
 1.65547983 1.63908894 1.62286034 1.60679241 1.59088358 1.57513225
 1.55953689 1.54409593 1.52880785 1.51367114 1.49868429 1.48384584
 1.46915429 1.45460821 1.44020615 1.42594668 1.4118284  1.3978499
 1.3840098  1.37030673 1.35673934 1.34330628 1.33000622 1.31683784
 1.30379984 1.29089093 1.27810983 1.26545528 1.25292602 1.24052081
 1.22823843 1.21607765 1.20403728 1.19211612 1.18031299 1.16862672
 1.15705616 1.14560016 1.13425758 1.12302731 1.11190822 1.10089923
 1.08999924

# 高斯-塞德尔

In [44]:
def Gauss_Seidel(A, b, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    #print('D=',D)
    #print('diag(D)=',np.diag(D))
    L = np.tril(A) - np.diag(D)
    #print('L=',L)
    U = np.triu(A) - np.diag(D)
    #print('U=',U)
    
    x_i = initial_guess * np.ones(n)
    x_ii = x_i.copy()
    
    for i in range(iter_n):
        for k in range(n):
            x_ii[k] = (b[k] - U[k].dot(x_i) - L[k].dot(x_ii)) / D[k]
        print('x_',i,'=',x_i)
        x_i = x_ii.copy()
        
    return x_i

In [39]:
a=np.array([1,2,3])
b1=a
b2=a.copy()

In [40]:
print(a,b1,b2)
b1[1]=0
print(a,b1,b2)

[1 2 3] [1 2 3] [1 2 3]
[1 0 3] [1 0 3] [1 2 3]


In [55]:
print(a,b1,b2)
b2[1]=0
print(a,b1,b2)

[1 2 3] [1 2 3] [1 2 3]
[1 2 3] [1 2 3] [1 0 3]


In [41]:
A=np.array([[3, 1],
             [1,2]])
b=np.array([5,5])
x0=np.array([0,0])
print(Gauss_Seidel(A,b,20,x0))

x_ 0 = [0. 0.]
x_ 1 = [1.66666667 1.66666667]
x_ 2 = [1.11111111 1.94444444]
x_ 3 = [1.01851852 1.99074074]
x_ 4 = [1.00308642 1.99845679]
x_ 5 = [1.0005144 1.9997428]
x_ 6 = [1.00008573 1.99995713]
x_ 7 = [1.00001429 1.99999286]
x_ 8 = [1.00000238 1.99999881]
x_ 9 = [1.0000004 1.9999998]
x_ 10 = [1.00000007 1.99999997]
x_ 11 = [1.00000001 1.99999999]
x_ 12 = [1. 2.]
x_ 13 = [1. 2.]
x_ 14 = [1. 2.]
x_ 15 = [1. 2.]
x_ 16 = [1. 2.]
x_ 17 = [1. 2.]
x_ 18 = [1. 2.]
x_ 19 = [1. 2.]
[1. 2.]


# 例3

In [45]:
A=np.array([[3, 1,-1],
             [2,4,1],[-1,2,5]])
b=np.array([4,1,1])
x0=np.array([0,0,0])
print('Jacobi')
print(Jacobi(A,b,20,x0))
print('Gauss_Seidel')
print(Gauss_Seidel(A,b,20,x0))

Jacobi
[3 4 5]
[[3 0 0]
 [0 4 0]
 [0 0 5]]
x_ 0 = [0. 0. 0.]
x_ 1 = [1.33333333 0.25       0.2       ]
x_ 2 = [ 1.31666667 -0.46666667  0.36666667]
x_ 3 = [ 1.61111111 -0.5         0.65      ]
x_ 4 = [ 1.71666667 -0.71805556  0.72222222]
x_ 5 = [ 1.81342593 -0.78888889  0.83055556]
x_ 6 = [ 1.87314815 -0.86435185  0.87824074]
x_ 7 = [ 1.91419753 -0.90613426  0.92037037]
x_ 8 = [ 1.94216821 -0.93719136  0.94529321]
x_ 9 = [ 1.96082819 -0.95740741  0.96331019]
x_ 10 = [ 1.97357253 -0.97124164  0.9751286 ]
x_ 11 = [ 1.98212341 -0.98056842  0.98321116]
x_ 12 = [ 1.98792653 -0.9868645   0.98865205]
x_ 13 = [ 1.99183885 -0.99112628  0.9923311 ]
x_ 14 = [ 1.99448579 -0.9940022   0.99481828]
x_ 15 = [ 1.99627349 -0.99594747  0.99649804]
x_ 16 = [ 1.99748184 -0.99726126  0.99763369]
x_ 17 = [ 1.99829831 -0.99814934  0.99840087]
x_ 18 = [ 1.99885007 -0.99874937  0.9989194 ]
x_ 19 = [ 1.99922292 -0.99915488  0.99926976]
[ 1.99947488 -0.9994289   0.99950654]
Gauss_Seidel
x_ 0 = [0. 0. 0.]
x_ 1 = [

# 连续过松弛 SOR

In [46]:
def SOR(A, b, w, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    L = np.tril(A) - np.diag(D)
    U = np.triu(A) - np.diag(D)
    
    x_i = initial_guess * np.ones(n)
    
    for i in range(iter_n):
        print('x_',i,'=',x_i)
        x_i = np.linalg.inv(w*L + np.diag(D)).dot((1 - w)*np.diag(D).dot(x_i) - w*U.dot(x_i)) + \
        w*np.linalg.inv(np.diag(D) + w*L).dot(b)
        
    return x_i

In [47]:
def SOR2(A, b, w, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    L = np.tril(A) - np.diag(D)
    U = np.triu(A) - np.diag(D)
    matinv=np.linalg.inv(w*L + np.diag(D))
    
    x_i = initial_guess * np.ones(n)
    
    for i in range(iter_n):
        print('x_',i,'=',x_i)
        x_i = matinv.dot((1 - w)*np.diag(D).dot(x_i) - w*U.dot(x_i)) + \
        w*matinv.dot(b)
        
    return x_i

In [48]:
A=np.array([[3, 1,-1],
             [2,4,1],[-1,2,5]])
b=np.array([4,1,1])
x0=np.array([0,0,0])
print(SOR2(A,b,1.25,20,x0))

x_ 0 = [0. 0. 0.]
x_ 1 = [ 1.66666667 -0.72916667  1.03125   ]
x_ 2 = [ 1.98350694 -1.0671658   1.02164714]
x_ 3 = [ 2.04112865 -1.01567869  1.01270972]
x_ 4 = [ 2.00154634 -1.00101858  0.99771844]
x_ 5 = [ 1.99908717 -0.99846185  0.99957311]
x_ 6 = [ 1.99940944 -0.99988203  0.9999001 ]
x_ 7 = [ 2.00005686 -1.00003381  1.0000561 ]
x_ 8 = [ 2.00002325 -1.00002361  1.00000359]
x_ 9 = [ 2.00000552 -0.99999867  0.99999982]
x_ 10 = [ 1.99999799 -0.99999902  0.99999905]
x_ 11 = [ 1.9999997  -0.99999976  1.00000004]
x_ 12 = [ 1.99999999 -1.00000007  1.00000002]
x_ 13 = [ 2.00000004 -1.00000001  1.00000001]
x_ 14 = [ 2. -1.  1.]
x_ 15 = [ 2. -1.  1.]
x_ 16 = [ 2. -1.  1.]
x_ 17 = [ 2. -1.  1.]
x_ 18 = [ 2. -1.  1.]
x_ 19 = [ 2. -1.  1.]
[ 2. -1.  1.]


In [52]:
A=np.array([[3, 1,-1],
             [2,4,1],[-1,2,5]])
b=np.array([4,1,1])
x0=np.array([0,0,0])
print(SOR(A,b,0.6,20,x0))

x_ 0 = [0. 0. 0.]
x_ 1 = [ 0.8    -0.09    0.2376]
x_ 2 = [ 1.18552    -0.277296    0.42385344]
x_ 3 = [ 1.41443789 -0.44882778  0.56699259]
x_ 4 = [ 1.56893923 -0.58526177  0.67553257]
x_ 5 = [ 1.67973456 -0.68935496  0.75722637]
x_ 6 = [ 1.76121009 -0.76768897  0.81848111]
x_ 7 = [ 1.82171805 -0.82636317  0.86432577]
x_ 8 = [ 1.86682501 -0.87024164  0.8986073 ]
x_ 9 = [ 1.90049979 -0.90303769  0.92423194]
x_ 10 = [ 1.92565384 -0.92754602  0.94338228]
x_ 11 = [ 1.9444472  -0.94585991  0.95769295]
x_ 12 = [ 1.95848945 -0.95954474  0.96838665]
x_ 13 = [ 1.96898206 -0.96977051  0.97637743]
x_ 14 = [ 1.97682241 -0.97741154  0.98234843]
x_ 15 = [ 1.98268096 -0.98312117  0.98681017]
x_ 16 = [ 1.98705865 -0.98738759  0.99014413]
x_ 17 = [ 1.9903298  -0.9905756   0.99263537]
x_ 18 = [ 1.99277411 -0.99295778  0.99449691]
x_ 19 = [ 1.99460058 -0.99473782  0.99588791]
[ 1.99596538 -0.99606793  0.99692731]


In [53]:
A=np.array([[3, 1,-1],
             [2,4,1],[-1,2,5]])
b=np.array([4,1,1])
x0=np.array([0,0,0])
print(SOR(A,b,2.0,20,x0))

x_ 0 = [0. 0. 0.]
x_ 1 = [ 2.66666667 -2.16666667  3.2       ]
x_ 2 = [ 3.57777778 -2.51111111  0.64      ]
x_ 3 = [ 1.18962963  1.50148148 -0.96533333]
x_ 4 = [-0.16750617 -0.35130864  1.57937778]
x_ 5 = [ 4.12129712 -4.05967737  3.71688296]
x_ 6 = [ 3.7297431  -1.02850722 -1.00217995]
x_ 7 = [-1.04552492  3.07512211 -1.47612771]
x_ 8 = [ 0.67802504 -2.5150833   4.15940437]
x_ 9 = [ 6.43830007 -5.50291895  3.21825082]
x_ 10 = [ 2.04247978  2.35131376 -3.88230992]
x_ 11 = [-3.53156223  3.62140343 -0.02743772]
x_ 12 = [ 3.76566813 -6.8733527   7.43238714]
x_ 13 = [ 8.43815843 -4.7809993   0.16767567]
x_ 14 = [-2.47237512  7.66953658 -6.89225498]
x_ 15 = [-4.56881925  0.84541017  4.78839915]
x_ 16 = [  9.86414524 -12.60375498   9.64026293]
x_ 17 = [ 7.6318667   0.65175681 -6.7089217 ]
x_ 18 = [-9.87231904 13.07502309 -7.30002438]
x_ 19 = [-1.04437927 -7.88063162 13.58677798]
[ 18.02265234 -16.4354097    7.17061072]


# 稀疏矩阵

In [54]:
import numpy as np
def A_ij(n):
    A = np.zeros((n, n))
    for i in range(n):
        A[i,n-1-i]=0.5
    for i in range(n):
        A[i, i] = 3
        if i < n-1:
            A[i, i+1] = -1
            A[i+1, i] = -1

    return A

def b_i(n):
    b=np.zeros(n)
    for i in range(n):
        b[i]=1.5
    b[0]=2.5
    b[n-1]=2.5
    n2=int(n/2)
    b[n2-1]=1
    b[n2]=1
    return b

In [55]:
print(A_ij(10))
print(b_i(10))

[[ 3.  -1.   0.   0.   0.   0.   0.   0.   0.   0.5]
 [-1.   3.  -1.   0.   0.   0.   0.   0.   0.5  0. ]
 [ 0.  -1.   3.  -1.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.  -1.   3.  -1.   0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.  -1.   3.  -1.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.  -1.   3.  -1.   0.   0.   0. ]
 [ 0.   0.   0.   0.5  0.  -1.   3.  -1.   0.   0. ]
 [ 0.   0.   0.5  0.   0.   0.  -1.   3.  -1.   0. ]
 [ 0.   0.5  0.   0.   0.   0.   0.  -1.   3.  -1. ]
 [ 0.5  0.   0.   0.   0.   0.   0.   0.  -1.   3. ]]
[2.5 1.5 1.5 1.5 1.  1.  1.5 1.5 1.5 2.5]


# 迭代

In [57]:
import numpy as np

def Jacobi(A, b, iter_n, initial_guess=0):
    n = len(A)
    D = np.diag(A)
    R = A - np.diag(D)
    x_i = initial_guess * np.ones(n)
    for i in range(iter_n):
        x_i = (b - R.dot(x_i)) / D
    return x_i

def Gauss_Seidel(A, b, iter_n, initial_guess=0):
    n = len(A)
    D = np.diag(A)
    L = np.tril(A) - np.diag(D)
    U = np.triu(A) - np.diag(D)
    x_i = initial_guess * np.ones(n)
    x_ii = x_i.copy()
    for i in range(iter_n):
        for k in range(n):
            x_ii[k] = (b[k] - U[k].dot(x_i) - L[k].dot(x_ii)) / D[k]
        x_i = x_ii.copy()
    return x_i

def SOR(A, b, w, iter_n, initial_guess=0):
    n = len(A)
    
    D = np.diag(A)
    L = np.tril(A) - np.diag(D)
    U = np.triu(A) - np.diag(D)
    matinv=np.linalg.inv(w*L + np.diag(D))
    
    x_i = initial_guess * np.ones(n)
    
    for i in range(iter_n):
        print('x_',i,'=',x_i)
        x_i = matinv.dot((1 - w)*np.diag(D).dot(x_i) - w*U.dot(x_i)) + \
        w*matinv.dot(b)
        
    return x_i

In [58]:
A=A_ij(10000)
b=b_i(10000)
x0=np.zeros(10000)

In [59]:
print('Jacobi: ',Jacobi(A,b,20,x0))

Jacobi:  [0.99992398 1.00013865 0.99981978 ... 0.99981978 1.00013865 0.99992398]


In [60]:
print('Gauss_Seidel: ',Gauss_Seidel(A,b,20,x0))

Gauss_Seidel:  [1.00005177 1.00009414 1.00013135 ... 0.99991024 0.99994084 0.99997165]


In [61]:
print('SOR: ',SOR(A,b,1.2,20,x0))

x_ 0 = [0. 0. 0. ... 0. 0. 0.]
x_ 1 = [1.         1.         1.         ... 0.66666667 0.66666667 1.06666667]
x_ 2 = [0.98666667 1.06133333 1.0912     ... 0.85659259 1.0237037  0.99881481]
x_ 3 = [1.02743704 1.03044741 1.06387911 ... 0.99569939 0.98697546 0.98953981]
x_ 4 = [1.00878359 1.02558051 1.02925363 ... 0.98483072 0.98723702 0.99523013]
x_ 5 = [1.00942946 1.01290973 1.02002008 ... 0.98882794 0.99359388 0.99650563]
x_ 6 = [1.00397687 1.00829806 1.01027894 ... 0.99427835 0.99593521 0.99827758]
x_ 7 = [1.00286833 1.00441226 1.00628478 ... 0.99650962 0.99784539 0.99890897]
x_ 8 = [1.00140944 1.00262616 1.00341105 ... 0.99810881 0.9987128  0.99942144]
x_ 9 = [1.00088429 1.00145034 1.0019974  ... 0.99888772 0.99929103 0.99965527]
x_ 10 = [1.00047223 1.00083958 1.00111774 ... 0.99937945 0.99958777 0.99980961]
x_ 11 = [1.00027946 1.00047341 1.00064405 ... 0.99964118 0.99976808 0.99988942]
x_ 12 = [1.00015559 1.00027156 1.00036593 ... 0.99979666 0.9998665  0.9999376 ]
x_ 13 = [1.0000899

# 高斯消元

In [62]:
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape

    for i in range(m):  #化为上三角矩阵
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]
    print('A1: ',A)

    for i in range(m-1, 0, -1): # 化为对角矩阵
        for j in range(i):
            A[j] -= A[j, i]*A[i]
    print('A2: ',A)        
            
    return A

In [63]:
A=A_ij(2000)
b=b_i(2000)
x0=np.zeros(2000)
b2=np.expand_dims(b,axis=0)
B=np.concatenate((A,b2.T),axis=1)
print(B)
print("x, y", Gaussian_elimination(B)[:, -1])

[[ 3.  -1.   0.  ...  0.   0.5  2.5]
 [-1.   3.  -1.  ...  0.5  0.   1.5]
 [ 0.  -1.   3.  ...  0.   0.   1.5]
 ...
 [ 0.   0.   0.5 ... -1.   0.   1.5]
 [ 0.   0.5  0.  ...  3.  -1.   1.5]
 [ 0.5  0.   0.  ... -1.   3.   2.5]]
A1:  [[ 1.         -0.33333333  0.         ...  0.          0.16666667
   0.83333333]
 [ 0.          1.         -0.375      ...  0.1875      0.0625
   0.875     ]
 [ 0.          0.          1.         ...  0.07142857  0.02380952
   0.9047619 ]
 ...
 [ 0.          0.          0.         ... -0.43135607 -0.00686439
   0.56177953]
 [ 0.          0.          0.         ...  1.         -0.42821612
   0.57178388]
 [ 0.          0.          0.         ...  0.          1.
   1.        ]]
A2:  [[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 1. 1.]]
x, y [1. 1. 1. ... 1. 1. 1.]


In [65]:
x0=np.zeros(2000)
print('SOR: ',SOR(A,b,1.2,5,x0))

x_ 0 = [0. 0. 0. ... 0. 0. 0.]
x_ 1 = [1.         1.         1.         ... 0.66666667 0.66666667 1.06666667]
x_ 2 = [0.98666667 1.06133333 1.0912     ... 0.85659259 1.0237037  0.99881481]
x_ 3 = [1.02743704 1.03044741 1.06387911 ... 0.99569939 0.98697546 0.98953981]
x_ 4 = [1.00878359 1.02558051 1.02925363 ... 0.98483072 0.98723702 0.99523013]
SOR:  [1.00942946 1.01290973 1.02002008 ... 0.98882794 0.99359388 0.99650563]
