# 回顾

In [1]:
import numpy as np
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape

    for i in range(m):  #化为上三角矩阵
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]
    print('A1: ',A)

    for i in range(m-1, 0, -1): # 化为对角矩阵
        for j in range(i):
            A[j] -= A[j, i]*A[i]
    print('A2: ',A)        
            
    return A

def LU(A):
    m = A.shape[0]
    L = np.identity(m)
    U = A.copy()

    for i in range(m):
        for j in range(i+1, m):
            if U[i, i] == 0:
                raise ValueError("The matrix contains a zero pivot.")
            a = U[j, i] / U[i, i]
            L[j, i] = a
            U[j] -= a * U[i]
    
    return L, U

def Usolve(U,b):
    m,n=U.shape
    k=b.size
    x=np.zeros(k)
    print(m,n,k)
    
    for i in range(n-1,-1,-1):
        x[i]=b[i]
        for j in range(i+1,n,1):
            x[i]=x[i]-U[i,j]*x[j]
        x[i]=x[i]/U[i,i]
    return x

def Lsolve(L,b):
    m,n=L.shape
    k=b.size
    x=np.zeros(k)
    print(m,n,k)
    
    for i in range(0,n,1):
        x[i]=b[i]
        for j in range(0,i,1):
            x[i]=x[i]-L[i,j]*x[j]
        x[i]=x[i]/L[i,i]
        print(x[i])
    return x

In [2]:
A=np.array( [[2,1,0,0], [0,1,2,0],[2,4,5,1],[8,5,0,3]], dtype=float)
B=np.array([1,1,2,0], dtype=float)
AB=np.array( [[2,1,0,0,1], [0,1,2,0,1],[2,4,5,1,2],[8,5,0,3,0]], dtype=float)

In [3]:
Gaussian_elimination(AB)

A1:  [[ 1.   0.5  0.   0.   0.5]
 [ 0.   1.   2.   0.   1. ]
 [-0.  -0.   1.  -1.   2. ]
 [ 0.   0.   0.   1.  -1. ]]
A2:  [[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0. -1.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  1. -1.]]


array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  1., -1.]])

In [4]:
L,U=LU(A)
print(L,U)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 3. 1. 0.]
 [4. 1. 2. 1.]] [[ 2.  1.  0.  0.]
 [ 0.  1.  2.  0.]
 [ 0.  0. -1.  1.]
 [ 0.  0.  0.  1.]]


In [5]:
y=Lsolve(L,B)
print(y)

4 4 4
1.0
1.0
-2.0
-1.0
[ 1.  1. -2. -1.]


In [6]:
x=Usolve(U,y)
print(x)

4 4 4
[ 1. -1.  1. -1.]


In [7]:
import numpy as np
x=np.array([[0, 3, 4], [2, 6, 4]])

# 向量范数

In [8]:
y=np.linalg.norm(x, axis=1,ord=2, keepdims=False)
print(y)
print(y.shape)
y=np.linalg.norm(x, axis=1,ord=2, keepdims=True)
print(y)
print(y.shape)
y=np.linalg.norm(x, axis=0,ord=2, keepdims=True)
print(y)
y=np.linalg.norm(x, axis=1,ord=np.inf, keepdims=True)
print(y)
y=np.linalg.norm(x, axis=1,ord=1, keepdims=True)
print(y)
y=np.linalg.norm(x, axis=0,ord=1, keepdims=True)
print(y)

[5.         7.48331477]
(2,)
[[5.        ]
 [7.48331477]]
(2, 1)
[[2.         6.70820393 5.65685425]]
[[4.]
 [6.]]
[[ 7.]
 [12.]]
[[2. 9. 8.]]


# 矩阵范数

In [9]:
y=np.linalg.norm(x, ord=1, keepdims=False)
print(y)

9.0


In [10]:
y=np.linalg.norm(x, ord=2, keepdims=False)
print(y)

8.82419564510368


In [11]:
eigs=np.linalg.eig(x.T.dot(x))
print(eigs)

(array([ 7.78664288e+01, -6.15274170e-16,  3.13357122e+00]), array([[-0.19062904, -0.76822128, -0.61114371],
       [-0.75578607,  0.51214752, -0.40803471],
       [-0.62645669, -0.38411064,  0.67824113]]))


In [12]:
np.sqrt(eigs[0])

<ipython-input-12-9d404d81f019>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(eigs[0])


array([8.82419565,        nan, 1.7701896 ])

In [13]:
y=np.linalg.norm(x, ord=np.inf, keepdims=False)
print(y)

12.0


# 例1

In [14]:
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape

    for i in range(m):  #化为上三角矩阵
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]
    print('A1: ',A)

    for i in range(m-1, 0, -1): # 化为对角矩阵
        for j in range(i):
            A[j] -= A[j, i]*A[i]
    print('A2: ',A)        
            
    return A

In [15]:
A = np.array([[1.0, 1.0, 2.0], [1.0001,1,2.0001]])
print("x, y", Gaussian_elimination(A)[:, -1])

A1:  [[ 1.  1.  2.]
 [-0.  1.  1.]]
A2:  [[ 1.  0.  1.]
 [-0.  1.  1.]]
x, y [1. 1.]


# 条件数

In [16]:
import numpy as np
def cond(A):  # inf-范数
    return abs(A).sum(axis=1).max() * abs(np.linalg.inv(A)).sum(axis=1).max()

In [17]:
a1=np.random.rand(30,30)
print('cond(a1): ',cond(a1))

cond(a1):  717.8074624553913


In [18]:
u=np.array([[1,-1,-1,-1], [0,1,-1,-1],[0,0,1,-1],[0,0,0,1]])
ui=np.array([[1,1,2,4], [0,1,1,2],[0,0,1,1],[0,0,0,1]])
uii=np.linalg.inv(u)
print(ui,uii)

[[1 1 2 4]
 [0 1 1 2]
 [0 0 1 1]
 [0 0 0 1]] [[1. 1. 2. 4.]
 [0. 1. 1. 2.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


In [19]:
cond(u)

32.0

In [20]:
y=np.linalg.norm(u,ord=np.inf, keepdims=True)
print(y)
y=np.linalg.norm(ui,ord=np.inf, keepdims=True)
print(y)

[[4.]]
[[8.]]


In [21]:
y=np.linalg.norm(u,ord=1, keepdims=True)
print(y)
y=np.linalg.norm(ui,ord=1, keepdims=True)
print(y)

[[4.]]
[[8.]]


In [22]:
y1=np.linalg.norm(u,ord=2, keepdims=True)
print(y1)
y2=np.linalg.norm(ui,ord=2, keepdims=True)
print(y2)
print(y1*y2)

[[2.26307741]]
[[5.47512225]]
[[12.39062548]]


# 例1

In [23]:
a=np.array([[1,1],[1.0001,1]])
print(cond(a))

40004.000099993355


In [24]:
y1=np.linalg.norm(a,ord=2, keepdims=True)
print(y1)
y2=np.linalg.norm(np.linalg.inv(a),ord=2, keepdims=True)
print(y2)
print(y1*y2)

[[2.00005]]
[[20000.5000125]]
[[40002.00007499]]


# 常见矩阵

In [25]:
a1=np.random.rand(30,30)
print('cond(a1): ',cond(a1))

cond(a1):  497.59915452975264


In [26]:
a1=np.random.rand(3,3,3)
print(a1)
a1[1,2,2]

[[[0.78325    0.2571094  0.82390183]
  [0.38230809 0.46735797 0.58001483]
  [0.61343363 0.3205744  0.5288327 ]]

 [[0.31684151 0.3334224  0.47866383]
  [0.72948916 0.63464668 0.27848344]
  [0.79831534 0.37572429 0.54656681]]

 [[0.28040089 0.83390191 0.06948554]
  [0.51218848 0.54540751 0.00811962]
  [0.54945265 0.31389468 0.8614962 ]]]


0.5465668141807097

In [27]:
a2=np.eye(3,3)
a2[2,2]=10**(-8)
print(a2)
print('cond(a2): ',cond(a2))

[[1.e+00 0.e+00 0.e+00]
 [0.e+00 1.e+00 0.e+00]
 [0.e+00 0.e+00 1.e-08]]
cond(a2):  100000000.0


In [28]:
a2=np.eye(10,12)
print(a2)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [29]:
def hilb(n):
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i, j] = 1/(i+j+1)
    return matrix

In [30]:
import numpy as np
print(hilb(2))
print(hilb(3))
print(hilb(4))
print(cond(hilb(30)))

[[1.         0.5       ]
 [0.5        0.33333333]]
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
2.0708969268259664e+19


# 淹没

In [31]:
import numpy as np
A = np.array([[10**(-20), 1.0, 1.0], [1.0,2.0,4.0]])
A2=np.array([[1.0,2.0,4.0], [10**(-20), 1.0, 1.0]])
print("here: ","x, y", Gaussian_elimination(A)[:, -1])
print("there: ", "x, y", Gaussian_elimination(A2)[:, -1])

A1:  [[ 1.e+00  1.e+20  1.e+20]
 [-0.e+00  1.e+00  1.e+00]]
A2:  [[ 1.  0.  0.]
 [-0.  1.  1.]]
here:  x, y [0. 1.]
A1:  [[1. 2. 4.]
 [0. 1. 1.]]
A2:  [[1. 0. 2.]
 [0. 1. 1.]]
there:  x, y [2. 1.]


In [32]:
A = np.array([[1.0,2.0],[10**(-20), 1.0]])
print(np.linalg.inv(A))
print(cond(A))

[[ 1.e+00 -2.e+00]
 [-1.e-20  1.e+00]]
9.0


In [33]:
A = np.array([[10**(-20), 1.0], [1.0,2.0]])
print(np.linalg.inv(A))
print(cond(A))

[[-2.e+00  1.e+00]
 [ 1.e+00 -1.e-20]]
9.0


# 实例

In [34]:
import numpy as np
def cond(A):  # inf-范数
    return abs(A).sum(axis=1).max() * abs(np.linalg.inv(A)).sum(axis=1).max()

In [35]:
def A_ij(n):
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i, j] = 5/(i + 2*j + 2)
    return matrix

In [36]:
print(A_ij(6))

[[2.5        1.25       0.83333333 0.625      0.5        0.41666667]
 [1.66666667 1.         0.71428571 0.55555556 0.45454545 0.38461538]
 [1.25       0.83333333 0.625      0.5        0.41666667 0.35714286]
 [1.         0.71428571 0.55555556 0.45454545 0.38461538 0.33333333]
 [0.83333333 0.625      0.5        0.41666667 0.35714286 0.3125    ]
 [0.71428571 0.55555556 0.45454545 0.38461538 0.33333333 0.29411765]]


In [37]:
print(cond(A_ij(10)))

131370135425813.03


In [38]:
n = 10

A = A_ij(n)
x = np.ones(n)
b = np.dot(A, x)

b2=np.expand_dims(b,axis=0)
B=np.concatenate((A,b2.T),axis=1)
xc2=Gaussian_elimination(B)[:, -1]

forward_error = abs(xc2 - x).max()
backward_error = abs(A.dot(xc2) - b).max()
error_mag_factor = (forward_error/abs(x).max()) / (backward_error/abs(b).max())

print('xc2: ',xc2)
print("Forward error: %e" % forward_error)
print("Backward error: %e" % backward_error)
print("Error magnification factor: %e" % error_mag_factor)

A1:  [[ 1.          0.5         0.33333333  0.25        0.2         0.16666667
   0.14285714  0.125       0.11111111  0.1         2.92896825]
 [ 0.          1.          0.95238095  0.83333333  0.72727273  0.64102564
   0.57142857  0.51470588  0.46783626  0.42857143  6.13655479]
 [ 0.          0.          1.          1.4         1.52727273  1.53846154
   1.5         1.44117647  1.3754386   1.30909091 11.09144024]
 [ 0.          0.          0.          1.          1.84615385  2.41758242
   2.77310924  2.97987616  3.0877193   3.13043478 17.23487575]
 [ 0.          0.          0.          0.          1.          2.29166667
   3.50490196  4.51947884  5.32163743  5.93478261 22.57246751]
 [ 0.          0.          0.          0.          0.          1.
   2.73684211  4.78947368  6.86554331  8.80505929 24.19691838]
 [ 0.          0.          0.          0.          0.          0.
   1.          3.18181818  6.27140974  9.89917907 20.35240702]
 [ 0.          0.          0.          0.          0

In [39]:
A.dot(xc2)

array([7.32242063, 5.90437289, 5.04969336, 4.45509753, 4.0080267 ,
       3.65509753, 3.36700105, 3.125997  , 2.92057248, 2.74285524])

In [40]:
b

array([7.32242063, 5.90437289, 5.04969336, 4.45509753, 4.0080267 ,
       3.65509753, 3.36700105, 3.125997  , 2.92057248, 2.74285524])