In [46]:
def conj_grad_method(A, b, initial_guess=0, iter_num=0):
    n = len(A)
    x = initial_guess * np.ones(n)
    r = b - A.dot(x)
    d = r
    
    if iter_num == 0:
        iter_num = n

    for i in range(iter_num):
        print("At", i, "\nx=",x,"\nr=",r,"\nd=",d,"\nAd=",A.dot(d),"\n")
        alpha = r.dot(r) / d.dot(A).dot(d)
        x = x + alpha*d
        beta = np.dot(r - alpha*A.dot(d), r - alpha*A.dot(d)) / r.dot(r)
        r = r - alpha*A.dot(d)
        d = r + beta*d
        
        if r.max() == 0:
            break
    
    return x

In [49]:
A=np.array([[1,-1,0],[-1,2,1],[0,1,2]],dtype=float)
xr=np.ones(3)
b=A.dot(xr)
print("A=",A)
print("b=",b)

xb=conj_grad_method(A,b,0,3)
print('conj_grad: ',xb)


A= [[ 1. -1.  0.]
 [-1.  2.  1.]
 [ 0.  1.  2.]]
b= [0. 2. 3.]
At 0 
x= [0. 0. 0.] 
r= [0. 2. 3.] 
d= [0. 2. 3.] 
Ad= [-2.  7.  8.] 

At 1 
x= [0.         0.68421053 1.02631579] 
r= [ 0.68421053 -0.39473684  0.26315789] 
d= [ 0.68421053 -0.28808864  0.42313019] 
Ad= [ 0.97229917 -0.83725762  0.55817175] 

At 2 
x= [0.41509434 0.50943396 1.28301887] 
r= [ 0.09433962  0.11320755 -0.0754717 ] 
d= [ 0.12139551  0.10181559 -0.05873977] 
Ad= [ 0.01957992  0.02349591 -0.01566394] 

conj_grad:  [1. 1. 1.]


In [1]:
def Gaussian_elimination(equation):
    A = equation.copy()
    m, n = A.shape

    for i in range(m):
        A[i] = A[i] / A[i, i]
        for j in range(i+1, m):
            A[j] -= A[j, i]*A[i]

    for i in range(m-1, 0, -1):
        for j in range(i):
            A[j] -= A[j, i]*A[i]
            
    return A

# 牛顿法

In [59]:
def Newton_Method(F, DF, x, iter_num=10**4):
    for i in range(iter_num):
        s = np.linalg.inv(DF(x)).dot(F(x))
        print('At',i,'x=',x, 'norm=',np.linalg.norm(s, ord=np.inf, keepdims=False))
        x -= s
    return x

In [60]:
def Newton_Method2(F, DF, x, iter_num=10**4):
    for i in range(iter_num):
        A = np.insert(np.array(F(x), dtype=float).reshape(-1, 1), [0], DF(x), axis=1)
        s = Gaussian_elimination(A)[:, -1]
        print('At',i,'x=',x)
        x -= s
    return x

# 例1

In [3]:
import numpy as np
def F(x):
    u, v = x
    f1 = v-u**3
    f2 = u**2+v**2-1
    
    return np.array([f1, f2]) 

def DF(x):
    u, v = x
    df1 = (-3*u**2, 1)
    df2 = (2*u , 2*v)
    
    return np.array([df1, df2])

In [4]:
import numpy as np
x0=np.array([1, 2],dtype=float)

In [5]:
x = Newton_Method(F, DF, x0,10)
print(x)

At 0 x= [1. 2.] norm= 1.0
At 1 x= [1. 1.] norm= 0.375
At 2 x= [0.875 0.625] norm= 0.06065088757396449
At 3 x= [0.82903635 0.56434911] norm= 0.0029962400964652037
At 4 x= [0.82604011 0.56361977] norm= 8.750438242508192e-06
At 5 x= [0.82603136 0.56362416] norm= 7.822279958384407e-11
At 6 x= [0.82603136 0.56362416] norm= 4.632272209439611e-17
At 7 x= [0.82603136 0.56362416] norm= 4.632272209439611e-17
At 8 x= [0.82603136 0.56362416] norm= 4.632272209439611e-17
At 9 x= [0.82603136 0.56362416] norm= 4.632272209439611e-17
[0.82603136 0.56362416]


In [6]:
x0=np.array([1, 2],dtype=float)
print('x0: ',x0)
print('F(x): ',F(x0))

x0:  [1. 2.]
F(x):  [1. 4.]


In [14]:
np.array(F(x0), dtype=float).reshape(-1, 1) #任意行 一列

array([[1.],
       [4.]])

In [15]:
DF(x0)

array([[-3.,  1.],
       [ 2.,  4.]])

In [16]:
np.insert(np.array(F(x0), dtype=float).reshape(-1, 1), [1], DF(x0), axis=1)

array([[ 1., -3.,  1.],
       [ 4.,  2.,  4.]])

In [17]:
x = Newton_Method2(F, DF, x0,10)
print(x)

At 0 x= [1. 2.]
At 1 x= [1. 1.]
At 2 x= [0.875 0.625]
At 3 x= [0.82903635 0.56434911]
At 4 x= [0.82604011 0.56361977]
At 5 x= [0.82603136 0.56362416]
At 6 x= [0.82603136 0.56362416]
At 7 x= [0.82603136 0.56362416]
At 8 x= [0.82603136 0.56362416]
At 9 x= [0.82603136 0.56362416]
[0.82603136 0.56362416]


# 例2 多根情况

In [66]:
import numpy as np
def F(x):
    u, v = x
    f1 = 6*u**3+u*v-3*v**3-4
    f2 = u**2-18*u*v**2+16*v**3+1
    
    return np.array([f1, f2]) 

def DF(x):
    u, v = x
    df1 = (18*u**2+v, u-9*v**2)
    df2 = (2*u-18*v**2 , -36*u*v+48*v**2)
    
    return np.array([df1, df2])

x0=np.array([2, 2],dtype=float)
x1=np.array([1, -1],dtype=float)
x2=np.array([-1, 1],dtype=float)
x3=np.array([complex(-1,-1), complex(-1,-1)])

In [62]:
x = Newton_Method(F, DF, x0,10)
print(x)

At 0 x= [2. 2.] norm= 0.6596774193548389
At 1 x= [1.37258065 1.34032258] norm= 0.2941938331568622
At 2 x= [1.07838681 1.05380123] norm= 0.07303712303922415
At 3 x= [1.00534969 1.00269262] norm= 0.005316010300139878
At 4 x= [1.00003368 1.00002244] norm= 3.36775454921177e-05
At 5 x= [1. 1.] norm= 1.1195720588027824e-09
At 6 x= [1. 1.] norm= 0.0
At 7 x= [1. 1.] norm= 0.0
At 8 x= [1. 1.] norm= 0.0
At 9 x= [1. 1.] norm= 0.0
[1. 1.]


In [63]:
x = Newton_Method(F, DF, x1,10)
print(x)

At 0 x= [ 1. -1.] norm= 0.36923076923076925
At 1 x= [ 0.93846154 -0.63076923] norm= 0.2144002353326956
At 2 x= [ 0.90210035 -0.416369  ] norm= 0.09794428732239696
At 3 x= [ 0.88937014 -0.31842471] norm= 0.023149454532921648
At 4 x= [ 0.88692997 -0.29527525] norm= 0.0012645281446828328
At 5 x= [ 0.88680976 -0.29401073] norm= 3.6815035595844707e-06
At 6 x= [ 0.88680942 -0.29400704] norm= 3.11338128773404e-11
At 7 x= [ 0.88680942 -0.29400704] norm= 2.4610310083102583e-17
At 8 x= [ 0.88680942 -0.29400704] norm= 2.4610310083102583e-17
At 9 x= [ 0.88680942 -0.29400704] norm= 2.4610310083102583e-17
[ 0.88680942 -0.29400704]


In [64]:
x = Newton_Method(F, DF, x2,10)
print(x)

At 0 x= [-1.  1.] norm= 0.5845272206303724
At 1 x= [-0.41547278  0.71060172] norm= 1.7790437804563934
At 2 x= [1.363571   0.91017182] norm= 0.341468858221965
At 3 x= [1.02210214 0.65607373] norm= 0.162755217467232
At 4 x= [0.88365647 0.49331851] norm= 0.03070636067685037
At 5 x= [0.86606776 0.46261215] norm= 0.000444299003436542
At 6 x= [0.86593888 0.46216785] norm= 6.757743558674019e-08
At 7 x= [0.86593892 0.46216792] norm= 3.0226440603995823e-15
At 8 x= [0.86593892 0.46216792] norm= 6.12674962712547e-17
At 9 x= [0.86593892 0.46216792] norm= 1.6524045275529335e-16
[0.86593892 0.46216792]


In [67]:
x = Newton_Method(F, DF, x3,10)
print(x)

At 0 x= [-1.-1.j -1.-1.j] norm= 0.4270562599708941
At 1 x= [-1.11557377-0.92868852j -1.42704918-1.00245902j] norm= 0.23663144035999237
At 2 x= [-0.99683777-0.96087163j -1.19250819-1.03384312j] norm= 0.07383633094621761
At 3 x= [-0.9880023 -0.99738549j -1.15815415-1.09920063j] norm= 0.006596769152729591
At 4 x= [-0.99124295-0.99733069j -1.16457809-1.10070077j] norm= 5.467667775877452e-05
At 5 x= [-0.99121901-0.99734269j -1.16452488-1.10071337j] norm= 3.768412743152707e-09
At 6 x= [-0.99121901-0.99734269j -1.16452488-1.10071338j] norm= 9.212308244384748e-16
At 7 x= [-0.99121901-0.99734269j -1.16452488-1.10071338j] norm= 7.945059005890909e-16
At 8 x= [-0.99121901-0.99734269j -1.16452488-1.10071338j] norm= 4.941403475726043e-16
At 9 x= [-0.99121901-0.99734269j -1.16452488-1.10071338j] norm= 1.2770919580131549e-15
[-0.99121901-0.99734269j -1.16452488-1.10071338j]


# Broyden 法

In [73]:
def Broyden_Method_I(F, x, A, iter_num=10**4):
    x = np.array(x, dtype=float)
    n = len(x)
    
    for i in range(iter_num):
        d_i = -np.linalg.inv(A).dot(F(x))
        D_i = F(x + d_i) - F(x)
        A += (D_i - A.dot(d_i)).reshape(n, 1).dot(d_i.reshape(1, n)) / d_i.dot(d_i)
        print('At',i,'x=',x, 'norm=',np.linalg.norm(d_i, ord=np.inf, keepdims=False))
        x += d_i
        
    return x   

In [74]:
def F(x):
    u, v = x
    f1 = u**3 - v**3 + u
    f2 = u**2 + v**2 - 1
    
    return np.array([f1, f2])

In [75]:
x_0 = (1, 1)
A = np.identity(2)
x = Broyden_Method_I(F, x_0, A, 50)
print(x)

At 0 x= [1. 1.] norm= 1.0
At 1 x= [0. 0.] norm= 0.6666666666666666
At 2 x= [0.         0.66666667] norm= 0.4999999999999999
At 3 x= [0.5   1.125] norm= 0.6221547440605979
At 4 x= [0.70627827 0.50284526] norm= 0.30657464769023235
At 5 x= [0.46849588 0.8094199 ] norm= 0.07436158658636592
At 6 x= [0.54285747 0.84105596] norm= 0.031519339021486924
At 7 x= [0.51133813 0.86776471] norm= 0.007324002831841049
At 8 x= [0.50760711 0.86044071] norm= 0.0009151173473065652
At 9 x= [0.50799393 0.86135582] norm= 5.89896712807776e-06
At 10 x= [0.50799205 0.86136172] norm= 6.265120395279732e-08
At 11 x= [0.507992   0.86136179] norm= 3.6019390897823303e-10
At 12 x= [0.507992   0.86136179] norm= 1.3691807129468507e-13
At 13 x= [0.507992   0.86136179] norm= 3.5811869840542484e-17
At 14 x= [0.507992   0.86136179] norm= 0.3587657550936198
At 15 x= [0.14922625 1.07184349] norm= 0.35876575509361974
At 16 x= [0.507992   0.86136179] norm= 5.583973317945365e-17
At 17 x= [0.507992   0.86136179] norm= 3.7708320984

In [71]:
def Broyden_Method_II(F, x, B, iter_num=10**4):
    x = np.array(x, dtype=float)
    n = len(x)
    
    for i in range(iter_num):
        d_i = -B.dot(F(x))
        D_i = F(x + d_i) - F(x)
        B += (d_i - B.dot(D_i)).reshape(n, 1).dot(d_i.reshape(1, n)).dot(B) / d_i.dot(B).dot(D_i)
        print('At',i,'x=',x, 'norm=',np.linalg.norm(d_i, ord=np.inf, keepdims=False))
        x += d_i
        
    return x

In [72]:
x_0 = (1, 2)
A = np.identity(2)
x = Broyden_Method_II(F, x_0, A, 10)
print(x)

At 0 x= [1. 2.] norm= 6.0
At 1 x= [ 7. -2.] norm= 9.345381526104383
At 2 x= [-2.34538153 -3.35742972] norm= 64.84242623905592
At 3 x= [42.35646787 61.48499652] norm= 63.56376337741125
At 4 x= [-4.28029123 -2.07876686] norm= 2.2541919548227995
At 5 x= [-6.53448318 -0.64937427] norm= 5.615299073445127
At 6 x= [-0.91918411 -4.06946509] norm= 8.039544118763661
At 7 x= [ 7.12036001 -8.63661313] norm= 9.11959616373572
At 8 x= [-1.99923615 -3.49046671] norm= 1.0556587242329574
At 9 x= [-3.05489488 -2.94027651] norm= 40.565993331479525
[ 37.51109845 -23.25071901]


# 总结

In [76]:
def Newton_Method(F, DF, x, iter_num=10**4):
    for i in range(iter_num):
        s = np.linalg.inv(DF(x)).dot(F(x))
        print('At',i,'x=',x, 'norm=',np.linalg.norm(s, ord=np.inf, keepdims=False))
        x -= s
    return x

def Broyden_Method_I(F, x, A, iter_num=10**4):
    x = np.array(x, dtype=float)
    n = len(x)
    
    for i in range(iter_num):
        d_i = -np.linalg.inv(A).dot(F(x))
        D_i = F(x + d_i) - F(x)
        A += (D_i - A.dot(d_i)).reshape(n, 1).dot(d_i.reshape(1, n)) / d_i.dot(d_i)
        print('At',i,'x=',x, 'norm=',np.linalg.norm(d_i, ord=np.inf, keepdims=False))
        x += d_i
        
    return x 

def Broyden_Method_II(F, x, B, iter_num=10**4):
    x = np.array(x, dtype=float)
    n = len(x)
    
    for i in range(iter_num):
        d_i = -B.dot(F(x))
        D_i = F(x + d_i) - F(x)
        B += (d_i - B.dot(D_i)).reshape(n, 1).dot(d_i.reshape(1, n)).dot(B) / d_i.dot(B).dot(D_i)
        print('At',i,'x=',x, 'norm=',np.linalg.norm(d_i, ord=np.inf, keepdims=False))
        x += d_i
        
    return x

In [77]:
import numpy as np
def F(x):
    u, v = x
    f1 = u**2+v**2-1
    f2 = (u-1)**2+v**2-1
    
    return np.array([f1, f2]) 

def DF(x):
    u, v = x
    df1 = (2*u, 2*v)
    df2 = (2*(u-1) , 2*v)
    
    return np.array([df1, df2])

x_0 = (1, 1)
x_1 = (0, -1)
A = np.identity(2)
B = np.identity(2)

In [84]:
x = Newton_Method(F, DF, x_0,10)
print(x)

At 0 x= (1, 1) norm= 0.5
At 1 x= [0.5 1. ] norm= 0.125
At 2 x= [0.5   0.875] norm= 0.008928571428571428
At 3 x= [0.5        0.86607143] norm= 4.602356406479071e-05
At 4 x= [0.5        0.86602541] norm= 1.2229251689478724e-09
At 5 x= [0.5       0.8660254] norm= 6.409875621278547e-17
At 6 x= [0.5       0.8660254] norm= 0.0
At 7 x= [0.5       0.8660254] norm= 0.0
At 8 x= [0.5       0.8660254] norm= 0.0
At 9 x= [0.5       0.8660254] norm= 0.0
[0.5       0.8660254]


In [83]:
x = Broyden_Method_I(F, x_0, A, 10)
print(x)

At 0 x= [1. 1.] norm= 0.4900472323315072
At 1 x= [0.50995277 1.37493869] norm= 2.0555608287226352
At 2 x= [0.48441772 3.43049952] norm= 2.2977703356460655
At 3 x= [0.50007666 1.13272919] norm= 0.11716275817172388
At 4 x= [0.50000518 1.01556643] norm= 0.13091327146728443
At 5 x= [0.49999956 0.88465316] norm= 0.017160692565920746
At 6 x= [0.49999999 0.86749247] norm= 0.0014514953006824578
At 7 x= [0.5        0.86604097] norm= 1.5553306702430456e-05
At 8 x= [0.5        0.86602542] norm= 1.291154931761529e-08
At 9 x= [0.5       0.8660254] norm= 1.2824567231273286e-12
[0.5       0.8660254]


In [82]:
x = Broyden_Method_II(F, x_0, B, 10)
print(x)

At 0 x= [1. 1.] norm= 0.5
At 1 x= [0.5        1.13421889] norm= 0.36461762171152073
At 2 x= [0.5        1.49883651] norm= 0.5683552587380912
At 3 x= [0.5        0.93048125] norm= 0.04766579297795012
At 4 x= [0.5        0.88281546] norm= 0.01619323070153402
At 5 x= [0.5        0.86662223] norm= 0.0005910950199320726
At 6 x= [0.5        0.86603113] norm= 5.72597588437614e-06
At 7 x= [0.5        0.86602541] norm= 1.9730203646731757e-09
At 8 x= [0.5       0.8660254] norm= 6.40987524059745e-15
At 9 x= [0.5       0.8660254] norm= 0.0
[0.5       0.8660254]


/Users/jinmianli/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in true_divide
